### ISSUE TITLE
Using @ sigils with from-json on arrays creates a nested array

### ISSUE THREAD

**Issue by Kaiepi** [timo/json_fast#53]
Pretty self-explanatory:
```
bastille% perl6 -MJSON::Fast -e 'say from-json "[]"'
[]
bastille% perl6 -MJSON::Fast -e 'say my @ = from-json "[]"' 
[[]]
```

**Comment by timo** [comment]
unfortunately that's part of JSON::Fast being a drop-in replacement for JSON::Tiny. I want to have something in the future that'd get rid of the scalar container there, but I'm not yet sure what it should look like

**Comment by Antisunny** [comment]
**Environment**: Perl 6.d 2019.03;
**OS**: MacOS Mojave 14.5

Has this issue been solved? @timo 

# Issues:

```perl6
my %data = from-json '[]';
```
should thow a Error of **Type Mismatch**; actually got a `{}` hash type object; This's unacceptable.

```perl6
my @data = from-json '[]';
```
should not wrap another Array outside of the real data; actually got `[[]]`。

but
```perl6
my $data = from-json '[]';
```
got the right data: `[]`。

## Hash parsed correctly

The hash is parsed correctly.

```perl6
my %data = from-json '{}';
my $data = from-json '{}';

say $data.WHAT, %data.WHAT;  # (Hash)(Hash)
```

**Comment by Kaiepi** [comment]
FWIW you can deal with this by using `:=` instead of `=`:
```
bastille% perl6 -MJSON::Fast -e 'say my @ := from-json "[]"'
[]
```

**Comment by timo** [comment]
the solution for this is to use the `immutable` option for from-json, which results in List an Map instead of Array and Hash, and also strips containerization from outside, which allows you to just assign to % and @ sigiled variables. just changing the original way this works was not an option for json::fast's intended use as a drop-in replacement of JSON::Tiny, unfortunately
